name: makepkg

on: [push, pull_request]

jobs:
  pkgbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Makepkg Build and Check
      id: makepkg
      uses: edlanglois/pkgbuild-action@v1
      with:
        makepkgArgs: API_ID=${{ secrets.API_ID }} API_HASH=${{ secrets.API_HASH }}
    - name: Print Package Files
      run: |
        echo "Successfully created the following package archive"
        echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"
    - name: Upload Package Archive
      uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.makepkg.outputs.pkgfile0 }}
